# Global configuration

debug: false

# Locations

source: .
destination: ./_site
posts: ./_posts
includes: ./_includes
layouts: ./_layouts
plugins: ./_plugins
include: [.htaccess]

# Reading

env: 'dev'
exclude: [composer.json]
markdown_ext: [markdown,mkd,mkdn,md]
processable_ext: [html,htm,xml,js,css]
layout_ext: [html.twig,twig,html]
permalink: pretty
drafts: false

# Outputting

url: ''                                 # e.g: http://my-domain.local:4000
paginate: 0
paginate_path: 'page:num'
limit_posts: 0
timezone: null                          # e.g. Europe/Madrid
safe: false

# Serving
host: '0.0.0.0'
port: 4000

# Deprecated:

baseurl: '/'
relative_permalinks: true
