# Default configuration

debug: false

# Reading
env: 'dev'
drafts: false
markdown_ext: ['markdown', 'mkd', 'mkdn', 'md']
text_extensions: [ 'htm', 'html', 'html.twig', 'twig.html', 'twig', 'js', 'less', 'markdown', 'md', 'mkd', 'mkdn', 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'slim', 'txt', 'xhtml', 'xml' ]
attribute_syntax: 'yaml'
map_converter_extension:
  'html.twig': 'html'
  'twig.html': 'html'
  'twig': 'html'

# Outputting
include: []
exclude: []
timezone: 'UTC'                          # e.g. Europe/Madrid
safe: false
permalink: 'pretty'
preserve_path_title: false
no_html_extension: false
layout_ext: ['html.twig', 'twig', 'html']
url: ''                                  # e.g: http://your-domain.local:4000

avoid_renderizer:
  filename_extensions: ['css', 'js']
  paths: ['assets', 'bower_components', 'node_modules'] # relative to `content` folder

# Collections
collections:
  posts:
    output: true
    sort_by: 'date'
    sort_type: 'descending'

# Themes
themes:
  name: ''

# Data sources
data_sources:
  filesystem:
    class: 'Yosymfony\Spress\Core\DataSource\Filesystem\FilesystemDataSource'
    arguments:
      source_root: '%site_dir%/src'
      include: '%include%'
      exclude: '%exclude%'
      text_extensions: '%text_extensions%'
      attribute_syntax: '%attribute_syntax%'
      avoid_renderizer_path: '%avoid_renderizer_path%'
      avoid_renderizer_extension: '%avoid_renderizer_extension%'

# Plugins
plugin_manager_builder:
  exclude_path: ['tests', 'Tests']
