# Default configuration

debug: false

# Reading
env: 'dev'
drafts: false
markdown_ext: ['markdown', 'mkd', 'mkdn', 'md']

# Outputting
timezone: 'UTC'                          # e.g. Europe/Madrid
safe: false
permalink: 'pretty'
preserve_path_title: false

# Collections
collections:
  posts:
    output: true

# Data sources
data_sources:
  filesystem:
    class: 'Yosymfony\Spress\Core\DataSource\Filesystem\FilesystemDataSource'
    arguments:
      source_root: ./src
      include: [.htaccess]
      text_extensions: [ 'htm', 'html', 'html.twig', 'twig,html', 'js', 'less', 'markdown', 'md', 'mkd', 'mkdn', 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'slim', 'txt', 'xhtml', 'xml' ]
      attribute_syntax: "yaml"
